[keywords]
SLAM = ["SLAM", "Visual Odometry"]
SFM = ["SFM", "Structure from Motion"]
LLM = ["LLM", "Large Language Model", "GPT", "LLaMA"]
SAM = ["SAM", "Segement Anything"]
CLIP = ["CLIP", "BLIP", "Contrastive Language-Image Pre-Training"]
DINO = ["DINO", "DINOv2"]
